### ISSUE TITLE
Send tab is not available

### ISSUE THREAD

**Issue by nukeador** [mozilla/firefox-preview-bughunting-campaign#2]
**Fenix Version:** Mozilla/5.0 (Android 6.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Device:** Huawei Honor 7
**Android Version:** 6.0
**Issue Type:** Functional (doesn’t behave as expected)
**Tried in other browser**: ☐
**GitHub Username**: @nukeador

## Steps to Reproduce
Click menu and share url.
## Expected Behavior
Send to device menu appers
## Actual Behavior
I suspect it's not implemented yet but Send tab to other Firefox is not available

**Comment by lobontiumira** [comment]
Send to device is not implemented, but send a tab to another Firefox page works.
I will close this as invalid.
