### ISSUE TITLE
[BUG]All Android Firefoxes lack integration with native autocompletion

### ISSUE THREAD

**Issue by yurikoles** [mozilla/firefox-preview-bughunting-campaign#502]
**Firefox Preview Vesrsion**
1.0.0 (Build #11721515 🦎 68.0-20190611143747)
Friday 6/21 @ 3:15 PM

**What Android device are you using?**
Xiaomi Mi A1 (tissot).

**What Android Version are you using?**
LineageOS 16.0 (Android 9).

**Issue Type**
- [x] Functional (doesn’t behave as expected)
- [x] Android app related (bugs not inside the browser)

**Issue description**
1. Tap on any text field.
2. Open built-in pop-up menu.
3. Menu seems to be customized and doesn't contain “Autocomplete” item. 

**What were you hoping/expecting the browser to do?**
The menu must contain autocomplete item, so username/password may be filled from password manager.

**Actual behavior**
The menu is customized and lacks integration with native autocompletion, e.g. password managers. It seems to be shown only when there is something in clipboard and contains only “Paste” item.

**Screenshots**
I can't provide screenshot from Firefox since menu even doesn't pops-up when clipboard is empty.

Here is a screenshot of wanted behavior from Chrome:
![Screenshot_20190629-223349_Chrome_Beta (1)](https://user-images.githubusercontent.com/922873/60388816-39c2a780-9abf-11e9-9d31-95e4a3fc9e78.png)

Sorry for localization, it's a translation of “autocompletion”.

**Did you try in another browser**
- [x] yes, it works well in Chrome.

**Comment by sv-ohorvath** [comment]
Autofill is not yet implemented in Fenix, see: https://github.com/mozilla-mobile/fenix/issues/230
Password management only works with 3rd party pass managers for now. 
If these don't answer your concerns, please reopen the bug. thank you!
